M48
; DRILL file {KiCad (6.0.1)} date Sun Feb  6 00:08:49 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-06T00:08:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.600
%
G90
G05
T1
X55.055Y-93.345
T2
X29.72Y-53.4
X29.72Y-104.4
T0
M30
