M48
; DRILL file {KiCad (6.0.1)} date Wed Mar  2 00:16:32 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-02T00:16:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.600
%
G90
G05
T1
X77.47Y-75.755
T2
X44.96Y-55.94
X44.96Y-106.94
T0
M30
